### ISSUE TITLE
Adding Files Type

### ISSUE THREAD

**Issue by danielevz** [fldtrace/user-private-files-plugin#1]
Currently it only supports PDF files and i know there are some instructions for extending the file type but they dont work.

After adding more file types it still just supports pdf:

I added the fallowing:  
// Setup the array of supported file types. In this case, it's just PDF.
$supported_types = array('application/pdf','image/png','application/zip','image/jpg');

But when uploading a new file i still get the error:

"The file type that you've uploaded is not a PDF."

Maybe there is something missing, can you please help , Thank You for building this great and simple to use plugin.

**Comment by fldtrace** [comment]
try space after comma:

$supported_types = array('application/pdf', 'image/png', 'image/jpg');

**Comment by danielevz** [comment]
Thank You for your response , Now png also work but not jpg.

```
                           // Setup the array of supported file types. In this case, it's just PDF.

                           $supported_types = array('application/pdf', 'image/png', 'application/zip', 'image/jpg');
```

**Comment by fldtrace** [comment]
Try this line:
$supported_types = array('application/pdf', 'image/jpg');

Then ensure you're uploading a different actual jpeg or jpg file. In most cases the file could be corrupt or is encoded as other file format.
