### ISSUE TITLE
Show only one category

### ISSUE THREAD

**Issue by carloscartovar** [fldtrace/user-private-files-plugin#2]
Great plugin my friend! is been pretty useful in a personal project I'm doing. 
I don't know if this is the place a for a question, if there is a way to only show one category since the beginning (not having to use the dropdown) Where and what do I have to modify in the code?

Thanks again for your work!

**Comment by fldtrace** [comment]
If I understand correctly you only want to show posts from a specific category? You'll need to modify the plugin directly for that or hire somebody who can write PHP.
In any case you should look at this query and filter.
`$args = array(
        'post_type' => 'userfile',
        'meta_key' => 'upf_user', 
        'meta_value' => $current_user->user_login,
        'orderby' => 'date',
        'order' => DESC,
                terms' => array( 7 )
    );`
Where 7 is you term id. It can also be the actual name like so: 'my category'.

It will probably need other customization..
